import React from 'react'
import { useRouter } from 'next/router'
import Navbar from '../../components/Navbar'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
export const getStaticPaths = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts')
  const data = await response.json(response);
  const paths = data.map((e) => {
    return {
      params: {
        slug: e.id.toString()
      },

    }
  })
  return {
    paths,
    fallback: false,
  }
}
export const getStaticProps = async (context) => {
  const id=context.params.slug;
  const response = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`)
  const data = await response.json(response);
  return {
    props: {
      data: data
    }
  }
}
const slug = ({data}) => {
  const router = useRouter();
  const { slug } = router.query;
  return (
    <>

      <Head>
        <title>Hunter coder</title>
        <link rel="shortcut icon" href="Blogger_icon.png" type="image/x-icon" />
        <meta name="description" content="Generated by create next app" />

      </Head>

      <Navbar />
     

      <div className={styles.container}>
     

              <div className={styles.blog} key={data.id}>
                <div className={styles.blogno}>
                  <h2 className={styles.no}>{data.id}</h2>
                </div>

                <h3 className={styles.content}>
                {data.body} </h3>
              </div>





      </div>
    </>
  )
}

export default slug 