import React from 'react'
import Navbar from '../components/Navbar'
import Head from 'next/head'

function about() {
  return (
   <>
 <Head>
        <title>Hunter coder</title>
       <link rel="shortcut icon" href="Blogger_icon.png" type="image/x-icon" />
        <meta name="description" content="Generated by create next app" />
      
      </Head>
   <Navbar/>
   </>
  )
}

export default about