import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Link from 'next/link'

export const getStaticProps = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts')
  const data = await response.json(response);
  return {
    props: {
      data: data
    }
  }
}

export default function Home({ data }) {
  return (
    <>

      <Head>
        <title>Hunter coder</title>
        <link rel="shortcut icon" href="Blogger_icon.png" type="image/x-icon" />
        <meta name="description" content="Generated by create next app" />

      </Head>
      {/* <Script src=" /ind.js">

</Script> */}
      <Navbar />

      <div className={styles.container}>
        {
          data.map((e) => {
            return (

              <div className={styles.blog} key={e.id}>
                <div className={styles.blogno}>
                  <h2 className={styles.no}>{e.id}</h2>
                </div>

                <h3 className={styles.content}>
                  <Link href={`/blogpost/${e.id}`}>{e.body}</Link> </h3>
              </div>

            )
          })
        }




      </div>
    </>
  )
}
